---
title: Arrays gebruiken
hero_image: images/banner.png
description: Arrays gebruiken in Javascript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Arrays gebruiken in Javascript
