title: Using arrays in Javascript
hero_image: images/banner.png
description: Using arrays in Javascript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Using arrays in Javascript
